---
- hosts: production
  user: root
  vars:
    username: <username>
    password: <hashed username password> # mkpasswd --method=sha-512
    public_key: ~/.ssh/id_rsa.pub
  roles: 
   - common
   - ufw
   - user
   - nginx
   - php
   - mariadb
   - certbot
   - wp-cli
   - ssh
   - letsencrypt